# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ThreadOff
email: christian [/a.t.]donhofer.net
description: >- # this means to ignore newlines until "baseurl:"
  Virtual threads vs platform threads: ThreadOff can help you analyse whether 
  a certain task will work better with vThreads. It comes with a convenient UI,
  just add your tasks and run them, or simply explore the existing ones.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

domain: cdonhofer.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cdonhofer.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /ThreadOff/      # place folder name if the site is served in a subfolder


#twitter_username: cdonhofer
github_username:  cdonhofer
linkedin_profile: https://www.linkedin.com/in/christian-donhofer-527a59167/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - index.md
  - design.md
  - get-it.md
  - try-out-your-own-tasks.md
